Improve readability and make code more intuitive
MenschenToaster/CraftFlowers pull request #20
Opened 2022-08-18 06:27 UTC by TWME-TW

Improve readability and make code more intuitive

2022-08-18 14:57 UTC, TWME-TW commented
I don't know why there are still 48 Commits, there should be only 5.

2022-08-18 18:36 UTC, MenschenToaster approved these changes
I think the changes are pretty unnecessary, but I think its okay for now. Also, thanks for translating.

In the future, I want the language system to change to provide per player translations. That means, if player abc has the language de_DE in their client, the server should use de_DE for translating. (Optional of course. The current could still be used)

But for now this is fine. Can this be merged?

And the amounts of commits probably exists because I just squashed your last pull request into one commit. And your repository has 50 more commits than mine.

2022-08-18 18:37 UTC, MenschenToaster commented
And I would prefer if there are no major future changes done to the language file. Because if this is released, It's going to get ugly if every update breaks everything again.

2022-08-18 22:28 UTC, TWME-TW commented
Can be merged, this will be the last format change (unless typo,like Glow Berries --> Cave Vines)

2022-08-19 07:16 UTC, TWME-TW commented
> And I would prefer if there are no major future changes done to the language file. Because if this is released, It's going to get ugly if every update breaks everything again.

Maybe the file name will change if automatic language change is to be supported in the future

2022-08-19 15:29 UTC, MenschenToaster requested changes
Could you please remove the new listener and language class again? I think it's better if this gets merged first and the new language system gets added in the future.(If you don't mind, I would prefer if I implemented the new system). Since this PR creates syntax changes to the language file, I want this to be merged soon, so I can create a release.

2022-08-19 15:36 UTC, MenschenToaster requested changes

2022-08-19 15:36 UTC, MenschenToaster commented on src/main/resources/language.yml
> +  CAVE_VINES: "§2Cave Vines"
Is cave vines here really a better name? The icon is glow berries, and the vines are generally referred to as glow berries. Cave Vines is only the actual placed block. 

The community generally knows the block as glow berries, so we should keep that name

2022-08-19 16:16 UTC, TWME-TW commented
@MenschenToaster finished

2022-08-19 16:29 UTC, TWME-TW commented
> Could you please remove the new listener and language class again? I think it's better if this gets merged first and the new language system gets added in the future.(If you don't mind, I would prefer if I implemented the new system). Since this PR creates syntax changes to the language file, I want this to be merged soon, so I can create a release.

Ok "Automatic language" is up to you to write(I am still in the groping stage)(I'm not quite sure how to say this in English, so maybe it's weird?)

2022-08-19 17:12 UTC, MenschenToaster approved these changes

2022-08-19 17:14 UTC, merged